# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49e41b3d470b395b243c3f70afb373923c3bb7bab3aaef09c5ea7e8ab666f2191c51ecaa1431d731636bf12f8608f70477e6e428a6549378a3f62b95c1b95ff4

test:
  secret_key_base: 15fa7762cf311fd9412864fe997effc38218c29869a04913d5fb094074e3bdc62ccd0014e4aeadae164576a3c3e6c4d0bde8c46477eb7341c0b4d4be27189a56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
